try {
    throw Error(404)
} catch (error) {
    console.log(error)
}